SixIsland_GreenPath_Text_JaclynIntro:: @ 818B7B0
    .string "…Huh?\p"
    .string "I was envisioning my house, but\n"
    .string "this is where I TELEPORT?$"

SixIsland_GreenPath_Text_JaclynDefeat:: @ 818B7F0
    .string "Big boo-boo!$"

SixIsland_GreenPath_Text_JaclynPostBattle:: @ 818B7FD
    .string "I am so scatterbrained!\p"
    .string "I need to focus so I can TELEPORT\n"
    .string "properly to my house!$"

SixIsland_GreenPath_Text_LeftRouteSign:: @ 818B84D
    .string "GREEN PATH\n"
    .string "PATTERN BUSH AHEAD$"

SixIsland_GreenPath_Text_RightRouteSign:: @ 818B86B
    .string "GREEN PATH\n"
    .string "Think Green, Keep Nature Clean!$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BERRIES grow by soaking up sunlight.\p"
	.string "We help the BERRIES grow by watering\n"
	.string "them regularly.\p"
	.string "It's an expression of love, isn't it?$"

Route120_Text_YesYouUnderstand:
	.string "Yes, yes.\n"
	.string "You understand what I mean.\p"
	.string "You should take this.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… But it is important to make your\n"
	.string "own impressions, I guess…\p"
	.string "You can have this.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "I think that BERRY is rare.\n"
	.string "I hope you raise it with loving care.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "I'll get more BERRIES from\n"
	.string "the BERRY MASTER.$"