Route7_Text_UndergroundPathSign:: @ 8184097
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "I sometimes watch wild POKéMON\n"
	.string "gather BERRIES and leave them\l"
	.string "around spots like this!\p"
	.string "Here you go!\n"
	.string "You can have this one!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "I'm going to try really hard to find\n"
	.string "BERRIES in different colors.\p"
	.string "I hope you try hard, too!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "I wonder what color BERRIES I'll look\n"
	.string "for today?$"