ThreeIsland_House5_Text_ImNotLostelle:: @ 81A3469
    .string "Me?\n"
    .string "I'm not LOSTELLE.\p"
    .string "She's probably gone to the\n"
    .string "BERRY FOREST, I think.\p"
    .string "She picks BERRIES there for making\n"
    .string "lunch.$"

ThreeIsland_House5_Text_IllGoPlayWithLostelle:: @ 81A34DB
    .string "I think I'll go play with LOSTELLE\n"
    .string "today.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "You may call me the BERRY MASTER.\p"
	.string "I dream of filling the world with\n"
	.string "beautiful flowers, so I raise\l"
	.string "BERRIES and hand them out to\l"
    .string "everyone.\p"
	.string "You're deserving of one!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Why be stingy?\n"
	.string "Take another!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "If you ever head to the HOENN region,\n"
	.string "check out the flower shop near\l"
    .string "RUSTBORO CITY.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "I'm done for today.\n"
	.string "Come again another day.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "The way my husband grows BERRIES,\n"
	.string "oh, he's the best in the world.\p"
	.string "He makes me proud, that he does.\p"
	.string "Incidentally, child, have you heard\n"
	.string "a good saying lately?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! What a remarkable saying!\n"
	.string "Inspirational, it is!\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! A good saying it is.\n"
	.string "You're quite remarkable.\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Our four grandchildren should become\n"
	.string "more accomplished than my husband.\p"
	.string "Joy never goes out of my life!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"