Route1_Text_WorkAtPokeMartTakeSample:: @ 818329D
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls:: @ 8183347
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

Route1_Text_PutPotionAway:: @ 8183387
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's MEDICINE POCKET.$"

Route1_Text_CanJumpFromLedges:: @ 81833B9
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to PALLET TOWN\n"
    .string "quicker that way.$"

Route1_Text_RouteSign:: @ 818343A
    .string "ROUTE 1\n"
    .string "{UP_ARROW} VIRIDIAN CITY$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese: @ 82A7BB0
	.string "Hi, what's your name?\p"
	.string "… … …  … … …  … … …\n"
	.string "Okay. That's nice!\p"
	.string "My name is KIRI.\p"
	.string "My mommy and daddy named me that so\n"
	.string "I would grow healthy and\l"
    .string "warmhearted.\p"
	.string "That's what they wished.\p"
	.string "You can have one of these.$"

SootopolisCity_Text_GiveYouThisBerryToo: @ 82A7C7C
	.string "KIRI will give you this BERRY, too!\n"
	.string "I really like it lots!$"

SootopolisCity_Text_WhatKindOfWishInYourName: @ 82A7CB7
	.string "I wonder what kind of wish is included\n"
	.string "in your name.$"

SootopolisCity_Text_LikeSeasonBornIn: @ 82A7CEC
	.string "Spring, summer, autumn, and winter.\p"
	.string "If you're born in springtime, do you\n"
	.string "like the spring, and if you're born\l"
	.string "in the summer, do you like the summer?$"

SootopolisCity_Text_ThenILoveAutumn: @ 82A7D80
	.string "Then KIRI was born in the autumn,\n"
	.string "so I love the autumn!\p"
	.string "Which season do you like?$"

SootopolisCity_Text_OhDoesntMatter: @ 82A7DD2
	.string "Oh…\n"
	.string "It doesn't matter…\p"
	.string "There's so much that I want to know…$"
